<?php 
$pageTitle = 'WIKI Help';
$this->headTitle()->prepend($pageTitle);
?>
    <div id="content-body">
        <div id="wiki-content-left">
            <?php echo $this->menuLeft() ?>
            <?php echo $this->searchBox() ?>
        </div>
        <div id="wiki-content-main">
            <h2><?php echo $pageTitle ?></h2>    
            <div class="help">
                <h1>Editor Help</h2>

                <p><span class="bold">FONT STYLES</span></p>
                <p><span class="header1">Heading1</span>  {Heading1} - font-size: 140% font-weight: bold</p> 
                <p><span class="header2">Heading2</span>  {{Heading2}} - font-size: 120%, font-weight: bold</p>
                <p><span class="bold">Some Bold Text</span>  {{{Some Bold Text}}} - font-weight: bold

                <p><span class="bold">LINKS</span><p>
                <p>[Internal MyWiki Title]</p>  
                <p>[[External URL Title|ExternalURL] ex: [Zend Framework|http://framework.zend.com]</p>                
            </div>            
        </div>
    </div>
