#!/usr/bin/env php
<?php
/**
* .git/hooks/pre-commit
*
* This pre-commit hooks will check for PHP errors (lint), and make sure the
* code is PSR-2 compliant.
*
* Dependecy: PHP-CS-Fixer (https://github.com/fabpot/PHP-CS-Fixer)
*/
$exit = 0;
/*
* collect all files which have been added, copied or
* modified and store them in an array called output
*/
$output = array();
exec('git diff --cached --name-status --diff-filter=ACM', $output);
foreach ($output as $file) {
   if ('D' === substr($file, 0, 1)) {
       // deleted file; do nothing
       continue;
   }
   $fileName = trim(substr($file, 1));
   /*
    * Only PHP files
    */
   $extension = pathinfo($fileName, PATHINFO_EXTENSION);
   if (!preg_match('/^ph(p|tml)$/', $extension)) {
       continue;
   }
   /*
    * Check for parse errors
    */
   $output = array();
   $return = 0;
   exec("php -l " . escapeshellarg($fileName), $output, $return);
   if ($return != 0) {
       echo "PHP file fails to parse: " . $fileName . ":" . PHP_EOL;
       echo implode(PHP_EOL, $lintOutput) . PHP_EOL;
       $exit = 1;
       continue;
   }
}

exit($exit);

